apiVersion: 1

datasources:
  - name: Elasticsearch-logs
    uid: Elasticsearch-logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "morent-logs-*"
    editable: true
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5

  - name: Elasticsearch-heartbeat
    uid: Elasticsearch-heartbeat
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "morent-heartbeat-*"
    editable: true
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
