// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"user-system/app/controller"
	"user-system/app/repositories"
	"user-system/app/rpc"
	"user-system/app/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAuthController(db *gorm.DB) *controller.AuthController {
	userRepository := repositories.NewUserRepository(db)
	companyRepository := repositories.NewCompanyRepository(db)
	roleRepository := repositories.NewRoleRepository(db)
	authService := service.NewAuthService(userRepository, companyRepository, roleRepository)
	authController := controller.NewAuthController(authService)
	return authController
}

func InitUserController(db *gorm.DB) *controller.UserController {
	userRepository := repositories.NewUserRepository(db)
	companyRepository := repositories.NewCompanyRepository(db)
	roleRepository := repositories.NewRoleRepository(db)
	userService := service.NewUserService(userRepository, companyRepository, roleRepository)
	userController := controller.NewUserController(userService)
	return userController
}

func InitRoleController(db *gorm.DB) *controller.RoleController {
	roleRepository := repositories.NewRoleRepository(db)
	companyRepository := repositories.NewCompanyRepository(db)
	permissionRepository := repositories.NewPermissionRepository(db)
	roleService := service.NewRoleService(roleRepository, companyRepository, permissionRepository)
	roleController := controller.NewRoleController(roleService)
	return roleController
}

func InitCompanyController(db *gorm.DB) *controller.CompanyController {
	companyRepository := repositories.NewCompanyRepository(db)
	companyService := service.NewCompanyService(companyRepository)
	companyController := controller.NewCompanyController(companyService)
	return companyController
}

func InitRolePermissionController(db *gorm.DB) *controller.RolePermissionController {
	rolePermissionRepository := repositories.NewRolePermissionRepository(db)
	roleRepository := repositories.NewRoleRepository(db)
	permissionRepository := repositories.NewPermissionRepository(db)
	rolePermissionService := service.NewRolePermissionService(rolePermissionRepository, roleRepository, permissionRepository)
	rolePermissionController := controller.NewRolePermissionController(rolePermissionService)
	return rolePermissionController
}

func InitUserService(db *gorm.DB) service.UserService {
	userRepository := repositories.NewUserRepository(db)
	companyRepository := repositories.NewCompanyRepository(db)
	roleRepository := repositories.NewRoleRepository(db)
	userService := service.NewUserService(userRepository, companyRepository, roleRepository)
	return userService
}

func InitRoleService(db *gorm.DB) service.RoleService {
	roleRepository := repositories.NewRoleRepository(db)
	companyRepository := repositories.NewCompanyRepository(db)
	permissionRepository := repositories.NewPermissionRepository(db)
	roleService := service.NewRoleService(roleRepository, companyRepository, permissionRepository)
	return roleService
}

func InitRPCMethods(db *gorm.DB) *rpc.RPCMethods {
	companyRepository := repositories.NewCompanyRepository(db)
	companyService := service.NewCompanyService(companyRepository)
	userRepository := repositories.NewUserRepository(db)
	roleRepository := repositories.NewRoleRepository(db)
	userService := service.NewUserService(userRepository, companyRepository, roleRepository)
	permissionRepository := repositories.NewPermissionRepository(db)
	roleService := service.NewRoleService(roleRepository, companyRepository, permissionRepository)
	rolePermissionRepository := repositories.NewRolePermissionRepository(db)
	rolePermissionService := service.NewRolePermissionService(rolePermissionRepository, roleRepository, permissionRepository)
	rpcMethods := rpc.NewRPCMethods(companyService, userService, roleService, rolePermissionService)
	return rpcMethods
}

func InitRPCServer(db *gorm.DB) *rpc.RPCServer {
	companyRepository := repositories.NewCompanyRepository(db)
	companyService := service.NewCompanyService(companyRepository)
	userRepository := repositories.NewUserRepository(db)
	roleRepository := repositories.NewRoleRepository(db)
	userService := service.NewUserService(userRepository, companyRepository, roleRepository)
	permissionRepository := repositories.NewPermissionRepository(db)
	roleService := service.NewRoleService(roleRepository, companyRepository, permissionRepository)
	rolePermissionRepository := repositories.NewRolePermissionRepository(db)
	rolePermissionService := service.NewRolePermissionService(rolePermissionRepository, roleRepository, permissionRepository)
	rpcMethods := rpc.NewRPCMethods(companyService, userService, roleService, rolePermissionService)
	rpcServer := rpc.NewRPCServer(rpcMethods)
	return rpcServer
}
