server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    # Логи в stdout/stderr контейнера
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
